# Generated by Django 4.2.29 on 2026-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(default='vi', max_length=8)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'language'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('product_list_view', 'product_list_view'), ('product_detail_view', 'product_detail_view'), ('search', 'search'), ('add_to_cart', 'add_to_cart'), ('update_cart', 'update_cart'), ('remove_from_cart', 'remove_from_cart'), ('checkout_start', 'checkout_start'), ('order_created', 'order_created'), ('review_created', 'review_created'), ('chat_open', 'chat_open'), ('chat_message_sent', 'chat_message_sent'), ('chat_recommendation_click', 'chat_recommendation_click')], db_index=True, max_length=64)),
                ('product_type', models.CharField(blank=True, choices=[('computer', 'computer'), ('mobile', 'mobile'), ('clothes', 'clothes')], max_length=16)),
                ('product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category_id', models.PositiveIntegerField(blank=True, null=True)),
                ('query_text', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='vi', max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
